# custom config
demo:
  rabbitmq:
    enabled: false
  binance:
    apiKey: Uixyi4dlW7KP34ayGRECbLY9RNE7XIvoM4ADkQDktOo1IbTaJQp1j5x77N9kg6Bc
    secretKey: HLmPGiU8aGJ492SHYd8fhC6xa1S8yCCn3S4YYqlSS0JVKKP9ZUnI55mKJPERaw7T



server:
  port: 8765
  servlet:
    application-display-name: demo


spring:
  rabbitmq:
    host: 49.235.227.150
    port: 5672
    username: root
    password: root
  redis:
    host: 49.235.227.150
    password: 691216
    port: 6379
  datasource:
    url: jdbc:mysql://49.235.227.150:3306/cristina
    username: root
    password: '!QAZ2wsx'
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: demo2021


mybatis:
  mapper-locations: classpath*:com/jiangwei/demo/mapper/*.xml

logging:
  level:
    root: info