# custom config
demo:
  host: localhost
  rabbitmq:
    enabled: false



server:
  port: 8765
  servlet:
    application-display-name: demo


spring:
  rabbitmq:
    host: ${demo.host}
    port: 5672
    username: root
    password: root
  redis:
    host: ${demo.host}
    password: 691216
    port: 6379
  datasource:
    url: jdbc:mysql://${demo.host}:3306/cristina
    username: root
    password: Jwayy691216
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: demo2021


mybatis:
  mapper-locations: classpath*:com/jiangwei/demo/mapper/*.xml


logging:
  level:
    root: info